Repository openshift/aws-load-balancer-operator, pull requests merged in 2022-03, with the labels that each got.

#13 Add upstream CRDs to manifests
  Makefile
  bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml
  bundle/manifests/elbv2.k8s.aws_ingressclassparams.yaml
  bundle/manifests/elbv2.k8s.aws_targetgroupbindings.yaml
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  config/crd/kustomization.yaml
  config/samples/ingressclassparams.yaml
  config/samples/kustomization.yaml
  config/samples/targetgroupbindings-v1alpha1.yaml
  config/samples/targetgroupbindings-v1beta1.yaml
  hack/sync-upstream-crds.sh
Labels: approved, lgtm

#10 Add reconciliation for Credential Requests
  Dockerfile
  Makefile
  assets/iam-policy.json
  bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml
  cmd/iamctl/LICENSE
  cmd/iamctl/ast.go
  cmd/iamctl/const.go
  cmd/iamctl/main.go
  cmd/iamctl/minify.go
  cmd/iamctl/policy.go
  config/rbac/role.yaml
  docs/iamctl/iamctl.md
  docs/iamctl/iamctl_genpolicy.md
  go.mod
  go.sum
  main.go
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/credentials_request.go
  pkg/controllers/awsloadbalancercontroller/credentials_request_test.go
  pkg/controllers/awsloadbalancercontroller/credentialsrequest.go
  pkg/controllers/awsloadbalancercontroller/iam_policy.go
  pkg/controllers/awsloadbalancercontroller/subnettagging_test.go
  pkg/controllers/utils/test/events.go
  pkg/controllers/utils/test/vars.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash

#16 Add function to ensure default IngressClass
  api/v1alpha1/awsloadbalancercontroller_types.go
  bundle/manifests/networking.olm.openshift.io_awsloadbalancercontrollers.yaml
  config/crd/bases/networking.olm.openshift.io_awsloadbalancercontrollers.yaml
  main.go
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/ingressclass.go
  pkg/controllers/awsloadbalancercontroller/ingressclass_test.go
  pkg/controllers/awsloadbalancercontroller/status.go
  pkg/controllers/awsloadbalancercontroller/subnettagging_test.go
Labels: approved, lgtm

#17 Add functionality to ensure service for controller
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/service.go
  pkg/controllers/awsloadbalancercontroller/service_test.go
  pkg/controllers/awsloadbalancercontroller/webhooks.go
Labels: approved, lgtm

#18 Added ensure funcs for serviceaccounts and clusterroles
  bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/operator-credentials-request.yaml
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/credentials_request.go
  pkg/controllers/awsloadbalancercontroller/credentials_request_test.go
  pkg/controllers/awsloadbalancercontroller/ingressclass_test.go
  pkg/controllers/awsloadbalancercontroller/rbac.go
  pkg/controllers/awsloadbalancercontroller/rbac_clusterrole.go
  pkg/controllers/awsloadbalancercontroller/rbac_clusterrolebinding.go
  pkg/controllers/awsloadbalancercontroller/rbac_role.go
  pkg/controllers/awsloadbalancercontroller/rbac_rolebinding.go
  pkg/controllers/awsloadbalancercontroller/rbac_rules.go
  pkg/controllers/awsloadbalancercontroller/rbac_test.go
  pkg/controllers/awsloadbalancercontroller/service_test.go
  pkg/controllers/awsloadbalancercontroller/serviceaccount.go
  pkg/controllers/awsloadbalancercontroller/serviceaccount_test.go
  pkg/controllers/awsloadbalancercontroller/subnettagging_test.go
  pkg/controllers/utils/test/events.go
  pkg/controllers/utils/test/vars.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: approved, lgtm, tide/merge-method-squash

#14 Deployment ensure function
  README.md
  go.mod
  go.sum
  hack/operator-credentials-request.yaml
  main.go
  pkg/aws/aws.go
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/deployment.go
  pkg/controllers/awsloadbalancercontroller/deployment_test.go
  pkg/controllers/awsloadbalancercontroller/subnettagging_test.go
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/autoscaling/v2beta2/types.go
  vendor/k8s.io/api/autoscaling/v2beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/types.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1beta1/types.go
  vendor/k8s.io/api/flowcontrol/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/modules.txt
Labels: approved, lgtm

#20 Fixes for ensure deployment functionality
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/deployment.go
  pkg/controllers/awsloadbalancercontroller/deployment_test.go
Labels: approved, lgtm

#21 Fix RBAC rules
  pkg/controllers/awsloadbalancercontroller/rbac_rules.go
Labels: approved, lgtm

#23 Added AWS_DEFAULT_REGION environment variable
  main.go
  pkg/aws/aws.go
  pkg/aws/aws_test.go
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/deployment.go
  pkg/controllers/awsloadbalancercontroller/deployment_test.go
Labels: approved, lgtm

#26 Fix typo in leader election role
  pkg/controllers/awsloadbalancercontroller/rbac_rules.go
Labels: approved, lgtm, tide/merge-method-squash

#25 Mount AWS credentials from CredentialsRequest
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/credentials_request.go
  pkg/controllers/awsloadbalancercontroller/credentials_request_test.go
  pkg/controllers/awsloadbalancercontroller/deployment.go
  pkg/controllers/awsloadbalancercontroller/deployment_test.go
Labels: approved, lgtm

#19 Add functionality to ensure webhook
  main.go
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/deployment.go
  pkg/controllers/awsloadbalancercontroller/deployment_test.go
  pkg/controllers/awsloadbalancercontroller/service.go
  pkg/controllers/awsloadbalancercontroller/service_test.go
  pkg/controllers/awsloadbalancercontroller/webhooks.go
  pkg/controllers/awsloadbalancercontroller/webhooks_test.go
Labels: approved, lgtm

#27 Refactored resource names
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/credentials_request.go
  pkg/controllers/awsloadbalancercontroller/rbac_clusterrole.go
  pkg/controllers/awsloadbalancercontroller/rbac_clusterrolebinding.go
  pkg/controllers/awsloadbalancercontroller/rbac_role.go
  pkg/controllers/awsloadbalancercontroller/rbac_rolebinding.go
  pkg/controllers/awsloadbalancercontroller/rbac_test.go
  pkg/controllers/awsloadbalancercontroller/serviceaccount.go
  pkg/controllers/awsloadbalancercontroller/serviceaccount_test.go
Labels: approved, lgtm, tide/merge-method-squash

#28 Paginate through cluster subnets
  pkg/controllers/awsloadbalancercontroller/subnettagging.go
Labels: approved, lgtm

#30 Status improvements and conditions
  main.go
  pkg/controllers/awsloadbalancercontroller/controller.go
  pkg/controllers/awsloadbalancercontroller/credentials_request.go
  pkg/controllers/awsloadbalancercontroller/credentials_request_test.go
  pkg/controllers/awsloadbalancercontroller/ingressclass.go
  pkg/controllers/awsloadbalancercontroller/ingressclass_test.go
  pkg/controllers/awsloadbalancercontroller/serviceaccount.go
  pkg/controllers/awsloadbalancercontroller/serviceaccount_test.go
  pkg/controllers/awsloadbalancercontroller/status.go
  pkg/controllers/awsloadbalancercontroller/status_test.go
  pkg/controllers/awsloadbalancercontroller/subnettagging.go
  pkg/controllers/awsloadbalancercontroller/subnettagging_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: approved, lgtm

#31 Added a tutorial for the operator
  api/v1alpha1/awsloadbalancercontroller_types.go
  bundle/manifests/networking.olm.openshift.io_awsloadbalancercontrollers.yaml
  config/crd/bases/networking.olm.openshift.io_awsloadbalancercontrollers.yaml
  docs/tutorial.md
Labels: approved, lgtm

#33 Fixes naming issue in credentials request
  pkg/controllers/awsloadbalancercontroller/credentials_request.go
  pkg/controllers/awsloadbalancercontroller/credentials_request_test.go
Labels: approved, lgtm

#35 Added support for OwnNamespace
  bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml
  config/manifests/bases/aws-load-balancer-operator.clusterserviceversion.yaml
Labels: approved, px-approved, lgtm, docs-approved, qe-approved, tide/merge-method-squash

#37 Enable gosec linter
  .golangci.yaml
Labels: approved, px-approved, lgtm, docs-approved, qe-approved
