Repository openshift/aws-load-balancer-operator, pull requests merged in 2025-06, with the labels that each got.

#154 OWNERS: remove old and add new member of NID team
  OWNERS
Labels: approved, px-approved, lgtm, docs-approved, qe-approved

#158 NE-2064: Update controller image to latest available
  bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, px-approved, lgtm, docs-approved, qe-approved, jira/valid-reference

#161 OCPBUGS-57339: Use floating tag for controller image
  bundle/manifests/aws-load-balancer-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference
